name: Build & publish pytapas

# Trigger whenever pyproject.toml changes on the main branch
on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"


permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Delete old pypi deployments
        uses: strumwolf/delete-deployments@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pypi
          keep_latest: 4

